#週日 7月 12 00:11:59 2026
GamePath=D\:\\FF14\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn
DLanguage=CHS
SLanguage=JA
ReplaText=1
FLanguage=CSV
ReplaFont=0
SkipFiles=
TransMode=0
PatchedVersion=2026.06.18.0000.0000
