#週四 7月 09 23:03:42 2026
GamePath=D\:\\FF14\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn
DLanguage=CHS
SLanguage=JA
ReplaText=1
FLanguage=CSV
ReplaFont=0
SkipFiles=
TransMode=0
PatchedVersion=
