#週六 8月 08 10:09:25 2026
GamePath=D\:\\FF14\\SquareEnix\\FINAL FANTASY XIV - A Realm Reborn
DLanguage=CHS
SLanguage=JA
ReplaText=1
FLanguage=CSV
ReplaFont=0
SkipFiles=
TransMode=0
PatchedVersion=2026.08.05.0000.0000
BackupVersion=2026.08.05.0000.0000
